### ISSUE TITLE
Webpack run fails for plugin v.0.0.19

### ISSUE THREAD

**Issue by gbaldeck** [Kotlin/kotlin-frontend-plugin#11]
I am on Windows 7 and 10 with jdk 8 and Gradle 3.3.

This error only happens with the kotlin-frontend-plugin 0.0.19. Version 0.0.18 works fine.

![image](https://cloud.githubusercontent.com/assets/4185224/25707761/601b230e-3099-11e7-9a33-7f1c264054c9.png)

**Comment by cy6erGn0m** [comment]
@gbaldeck do you have full stacktrace?

**Comment by cy6erGn0m** [comment]
Ah I see why does it fail. You just need to clean your project.
