### ISSUE TITLE
Gradle 5.0  error NpmPackageManager$injectDependencies$1$1 does not define or inherit a method

### ISSUE THREAD

**Issue by apatrida** [Kotlin/kotlin-frontend-plugin#124]
This plugin fails hard under Gradle 5.0

> * What went wrong:
> Receiver class org.jetbrains.kotlin.gradle.frontend.npm.NpmPackageManager$injectDependencies$1$1 does not define or inherit an implementation of the resolved method getBuildDependencies()Lorg/gradle/api/tasks/TaskDependency; of interface org.gradle.api.file.FileCollection.

**Comment by JakeWharton** [comment]
#122

**Comment by snrostov** [comment]
Fixed in master. Will be released soon.
