### ISSUE TITLE
"No matching version found for kotlin@1.1.1" with NPM v5+

### ISSUE THREAD

**Issue by mikhalchenko-alexander** [Kotlin/kotlin-frontend-plugin#16]
OS: Mac OS Sierra
Node: 8.0.0
Npm: 5.0.1

Trying to build `examples/frontend-only` on Mac OS got this error. On Windows and Ubuntu build is successful.

    > gradlew build
    :npm-preunpack
    :npm-configure
    :npm-install
    npm ERR! code ETARGET
    npm ERR! notarget No matching version found for kotlin@1.1.1
    npm ERR! notarget In most cases you or one of your dependencies are requesting
    npm ERR! notarget a package version that doesn't exist.
    npm ERR! notarget
    npm ERR! notarget It was specified as a dependency of 'frontend-only'
    npm ERR! notarget
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /Users/name/.npm/_logs/2017-06-06T14_54_18_482Z-debug.log
    :npm-install FAILED
    
    FAILURE: Build failed with an exception.
    
    * What went wrong:
    Execution failed for task ':npm-install'.
    > npm install failed (exit code = 1)

    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

    BUILD FAILED

    Total time: 5.804 secs

*UPD:* It seems that problem is not related to OS. The problem caused by newer versions of npm. Npm v3.10.* which comes with Node v6.* is working as expected. But Npm v5.0.* which comes with Node v8.* ignores modules already installed in node_modules folder (in this case kotlin.js library) and tries to download it from npm repository.
The best solution I've found so far is to change
    
    "dependencies": {
      "kotlin": "1.1.2-4"
    }

to

    "dependencies": {
        "kotlin": "file:./node_modules/kotlin"
    }

and then `npm install` manually.
After that `gradlew bundle` is working properly. But after clean the above procedure should be repeated.

**Comment by vonox7** [comment]
@mikhalchenko-alexander In which file exactly did you change the dependencies for a workaround?

**Comment by channguyen** [comment]
@vonox7 The `/frontend/build` directory get generated each time I run gradle, and those values get back to their default values. Any suggestion?

**Comment by vonox7** [comment]
@channguyen Do you run just the frontend run task or more?

**Comment by nlwillia** [comment]
Note that on Windows, it's backslashes (ugh).
```
    "dependencies": {
        ...
        "kotlin": "file:.\\node_modules\\kotlin",
        "kotlin-test-js": "file:.\\node_modules\\kotlin-test-js",
        "kotlinx-html-js": "file:.\\node_modules\\kotlinx-html-js"
    },
```

**Comment by cy6erGn0m** [comment]
In 0.0.20 it should be fixed. 

Also there is a workaround: you can specify nodejs version

```
kotlinFrontend {
    downloadNodeJsVersion = "7.9.0"
```

Note that specifying nodejs version it will cause bundle downloading at first run

**Comment by mikhalchenko-alexander** [comment]
Yes, the plugin v0.0.20 is working as expected with the latest Node v8.2.1 and NPM v5.3.0. Thanks.
