### ISSUE TITLE
Specify webpack version

### ISSUE THREAD

**Issue by gbaldeck** [Kotlin/kotlin-frontend-plugin#17]
I need to specify the webpack and webpack-dev-server versions.

When I use 
`devDependency("webpack", "2.6.1")`
`devDependency("webpack-dev-server", "2.4.4")`

The package.json output still ends up as
`"webpack": "*"`
`"webpack-dev-server": "*"`

How do I specify the webpack and webpack-dev-server versions?

**Comment by cy6erGn0m** [comment]
Release in 0.0.20
