### ISSUE TITLE
не добавляются автоматически webpack пакет и его зависимости

### ISSUE THREAD

**Issue by team55** [Kotlin/kotlin-frontend-plugin#2]
Windows 10

сборка демо проекта frontend-only
module.js:471
    throw err;
    ^
Error: Cannot find module 'F:\!_KOTLIN\forks\kotlin-frontend-plugin\examples\frontend-only\build\node_modules\webpack\bin\webpack.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
:webpack-bundle FAILED

Если в каталоге Buid добавить вручную через npm install webpack, то все ок.
Изначально webpack присутствует в каталоге пакетов рядом с исполняемым файлов nodejs, но как видно в исходниках резолвится как project.buildDir.resolve("node_modules/webpack/bin/webpack.js")

Или необходимо что то прописать  в конфиге что бы собиралось автоматически нужное? (в примерах этого не нашел)

**Comment by cy6erGn0m** [comment]
webpack совершенно точно добавляется в зависимости. похоже на какую-то проблему с путями под windows (восклицательный знак после буквы диска выглядит подозрительно)

**Comment by cy6erGn0m** [comment]
fixed in 0.0.18

**Comment by Lewik** [comment]
Никогда не было и вот опять.
папки node-modules вообще нет. Но есть node-modules-imported но там вебпака нету
