### ISSUE TITLE
Is the order of the files in the `*. config.d` directory incorrect?

### ISSUE THREAD

**Issue by nosix** [Kotlin/kotlin-frontend-plugin#22]
The following description is in usage:

https://github.com/Kotlin/kotlin-frontend-plugin/blob/22ef064c1c2fcf1a7859a451d0d82e57bbbd3825/README.md#L127-L128

I created files and tried it as follows:

```
webpack.config.d
    10-config-20.js
    20-config-10.js
```
In the generated `webpack.config.js`, it is written as follows:

```
// from file .../webpack.config.d/20-config-10.js
{
   "name": "20-config-10"
}
// from file .../webpack.config.d/10-config-20.js
{
   "name": "10-config-20"
}
```

Is the order incorrect? The order is not decided by prefix.

I am sorry if it is a misunderstanding. If the order is incorrect, I think that if we correct the following code it will be fixed.

https://github.com/Kotlin/kotlin-frontend-plugin/blob/22ef064c1c2fcf1a7859a451d0d82e57bbbd3825/kotlin-frontend/src/main/kotlin/org/jetbrains/kotlin/gradle/frontend/npm/GeneratePackagesJsonTask.kt#L115

https://github.com/Kotlin/kotlin-frontend-plugin/blob/22ef064c1c2fcf1a7859a451d0d82e57bbbd3825/kotlin-frontend/src/main/kotlin/org/jetbrains/kotlin/gradle/frontend/webpack/GenerateWebPackConfigTask.kt#L117

**Comment by cy6erGn0m** [comment]
Fixed in 0.0.22, thanks!
