### ISSUE TITLE
The path of test is included in `resolve.modules` of `webpack.config.js`

### ISSUE THREAD

**Issue by nosix** [Kotlin/kotlin-frontend-plugin#23]
The following code seems to be executing filter to remove `compileTestKotlin2Js` task.

https://github.com/Kotlin/kotlin-frontend-plugin/blob/22ef064c1c2fcf1a7859a451d0d82e57bbbd3825/kotlin-frontend/src/main/kotlin/org/jetbrains/kotlin/gradle/frontend/webpack/GenerateWebPackConfigTask.kt#L67-L68

However, it is not filtered because `ignorecase = true` is not set.

Therefore, the path of test is also included in `resolve.modules` of `webpack.config.js`. Is this the expected behavior?

**Comment by cy6erGn0m** [comment]
Fixed, thanks!

**Comment by cy6erGn0m** [comment]
Fixed in 0.0.22
