### ISSUE TITLE
examples/frontend-only is out of date & broken

### ISSUE THREAD

**Issue by bootstraponline** [Kotlin/kotlin-frontend-plugin#27]
Uses gradle v3.2.1, Kotlin v1.1.1

It would be nice to keep the examples up to date.

**Comment by bootstraponline** [comment]
![image](https://user-images.githubusercontent.com/1173057/32410208-949e74c6-c191-11e7-9f1c-98d0c6ebcba0.png)
Also the example is broken out of the box. 😭 

Setting up CI for the examples will help keep them ✅

**Comment by cy6erGn0m** [comment]
Looks like it's a kotlin plugin issue that is unable to import proper build options from gradle. CI wouldn't help. Building in gradle works well. Perhaps Settings -> Build, Execution, Deployment -> Gradle -> Runner -> Delegate IDE builld/run actions could help if you use modern IDEA.

**Comment by cy6erGn0m** [comment]
It looks like it is already fixed in the latest kotlin (1.2.0 rc)
