### ISSUE TITLE
frontend-only example fails to build

### ISSUE THREAD

**Issue by bootstraponline** [Kotlin/kotlin-frontend-plugin#28]
I cloned master and opened `kotlin-frontend-plugin\examples\frontend-only\build.gradle` using IntelliJ IDEA 2017.2.5 Community Edition on Windows 10. Building the project produces:

![image](https://user-images.githubusercontent.com/1173057/32684247-cd573772-c64f-11e7-853c-0e38e46fb168.png)

Would you mind setting up a ` .travis.yml` that verifies these examples build correctly?

**Comment by cy6erGn0m** [comment]
What kotlin plugin version do you use? For sure project should be built via gradle.
You also can check fo r IDEA's settings `Build, Execution, Deployment -> Build Tools -> Gradle -> Runner`

In fact I already have CI configuration that is passing

**Comment by bootstraponline** [comment]
> In fact I already have CI configuration that is passing

I see it [passing on TeamCity](https://teamcity.jetbrains.com/viewType.html?buildTypeId=KotlinTools_KotlinFrontendPlugin_Build). ✅ 

> For sure project should be built via gradle.
> You also can check fo r IDEA's settings Build, Execution, Deployment -> Build Tools -> Gradle -> Runner -> Delegate IDE build/run actions to gradle

Thanks, that was not checked. It'd be great to add a readme to the examples folder mentioning this.
