### ISSUE TITLE
devServer.historyApiFallback

### ISSUE THREAD

**Issue by talon** [Kotlin/kotlin-frontend-plugin#34]
https://webpack.js.org/configuration/dev-server/#devserver-historyapifallback

I'd like to set this option on my devServer. Adding a new `webpack.config.d` file with this does not work.

```
config.devServer = {
    historyApiFallback: true
};
```

**Comment by abendt** [comment]
did you add a file _webpack.config.d_ or did you add a file (*.js) inside directory _webpack.config.d_?

**Comment by talon** [comment]
In the configuration directory

-------- Original Message --------

**Comment by talon** [comment]
Looks like that config is ignored either on purpose or because of a bug. However this seems like it should be exposed in `build.gradle` as one of the webpack options?
