### ISSUE TITLE
kotlin.js

### ISSUE THREAD

**Issue by talon** [Kotlin/kotlin-frontend-plugin#46]
"Its dependency 'kotlin' was not found. Please, check whether 'kotlin' is loaded prior to [module-js]"

This is a new error I'm receiving after trying to add a multi-platform project dependency to my app. Shouldn't the frontend plugin be bundling the kotlin runtime with my app code when I run `./gradlew -t run` or `./gradlew build`? It looks like this check is hard coded into the `module-js`?

**Comment by talon** [comment]
I needed to set the moduleKind on the multiplatform dep to "commonjs"

**Comment by Danilo-Araujo-Silva** [comment]
Can you share your `build.gradle.kts` or `build.gradle` configuration? I'm receiving the same error but changing to `commonjs` didn't solve the problem to me.

**Comment by Danilo-Araujo-Silva** [comment]
I've solved the problem with this configuration:

```
js("js") {
        configure(listOf(compilations["main"], compilations["test"])) {
            tasks.getByName(compileKotlinTaskName) {
                kotlinOptions {
                    //                    languageVersion = "1.3"
                    metaInfo = true
//                    outputFile = "${project.buildDir.path}/js/${project.name}.js"
                    sourceMap = true
                    sourceMapEmbedSources = "always"
                    moduleKind = "umd"
                }
            }
        }

        configure(listOf(compilations["main"])) {
            tasks.getByName(compileKotlinTaskName) {
                kotlinOptions {
                    main = "call"
                }
            }
        }
    }
```

My problem was that I was using two different modules, in two separated folders, the react app and the common module. But the common part that was being exported from the common module wasn't exporting the kotlin definition. After putting this configuration in both the react app and in the common it worked.
