### ISSUE TITLE
multi-module gradle build needs the webpack configuration to include resolution of sub modules output paths

### ISSUE THREAD

**Issue by apatrida** [Kotlin/kotlin-frontend-plugin#79]
If you have a multi-module build in Gradle, and the module using webpack depends on another module.  The current webpack configuration file that is created does not have a resolution entry for the dependent module.  Therefore webpack fails.

**Comment by JakeWharton** [comment]
Presumably you aren't using the DCE plugin as well, right? Because it would have copied the transitive closure into build/kotlin-js-min/main allowing the entire graph to be resolved. I see this behavior when the DCE plugin isn't applied as well.
