### ISSUE TITLE
Hot Replacement with multi project

### ISSUE THREAD

**Issue by danfma** [Kotlin/kotlin-frontend-plugin#8]
Suppose that you have multi projects and reference another with `compile project(...)`. When you execute `gradle run` it will start normally (very slow, but normally). But if you change any file referenced project, it won't update the browser with the last version until you clean and compile again (but that will take a lot of time again).

You can force the build but the linked project won't be updated again until the full rebuild.

**Comment by cy6erGn0m** [comment]
Unfortunately HMR with multimodule frontend project is not yet supported. Let me look at it what can I do

**Comment by cy6erGn0m** [comment]
Could you please tell me what does take so long in your configuration? Do you have frontend plugin in every module ?

**Comment by danfma** [comment]
Hey man! Probably what is getting it slow its the NPM. Try to add support to yarn as a configuration and I think that will resolve it.

**Comment by cy6erGn0m** [comment]
@danfma have you tried to configure [cache-min](https://docs.npmjs.com/misc/config#cache-min) in npmrc ?

**Comment by danfma** [comment]
No, I didn't know about that configuration setting of NPM. I will try it and then I give you a new feedback!

**Comment by danfma** [comment]
```

**Comment by cy6erGn0m** [comment]
I see, you have a lot of npm installs. Do you have tests in every module? Most likely you can omit dependencies in sub-modules that you don't run. You generally need npm and webpack only for final bundles (some module that you want to run).

**Comment by cy6erGn0m** [comment]
It should be fixed with 0.0.19

**Comment by danfma** [comment]
Thanks, man!

**Comment by danfma** [comment]
About what you have written before, when creation libraries I really don't need to create a bundle for it, but I still need the ability to generate the package.json correctly, that's why I used it on every project.

Give a look at my libraries (in maven until now): https://github.com/danfma/kodando. You will see that I have to generate a package for a project to then publish. 

I expect that, when I migrate to Gradle and start to use your plugin, I could generate that package.json automatically and get rid of the NPM publishing.

**Comment by cy6erGn0m** [comment]
there are two cases: in-project library dependency and external maven library dependency. 

When you have in-project library then you probably don't need package.json for library at all because every kotlin2js output file is in resolution paths list so there is no need to have package.json.

If there is a library written in kotlin2js and distributed as jar via maven then it may work without package.json as kotlin-frontend-plugin will generate it as well (as it does for kotlin-stdlib-js for example, you can see it in `build/node_modules/kotlin/package.json` - it is generated by the plugin).

So the only usecase is when you need to generate package.json is the case when you are going to publish your library to npm.

**Comment by danfma** [comment]
Ok, but in the second case, I want to create a binding to an external library (like React) and if I don't specify which library and version I'm using the frontend-plugin won't guess that. Am I wrong?

**Comment by cy6erGn0m** [comment]
good point, frontend-plugin is unable to see npm dependencies for external jar dependencies so there is no way to guess it without package.json.

What you need it ability to invoke package.json generation task (`npm-configure`) with no npm-install task. For now it's not so easy (possible but slightly difficult to discover how)

**Comment by danfma** [comment]
That's exactly what I'm trying to do! Will you work on this as a feature later? If you do it, then I can migrate to your plugin, but until there, I will have to wait.

:D
