### ISSUE TITLE
Plugin uses deprecated Gradle APIs

### ISSUE THREAD

**Issue by zvozin** [Kotlin/kotlin-frontend-plugin#90]
The `AbstractFileCollection.getBuildDependencies()` method  has been deprecated and is scheduled to be removed in Gradle 5.0. `org.jetbrains.kotlin.gradle.frontend.npm.NpmPackageManager$injectDependencies$1$1 extends AbstractFileCollection`. Don't do that, use `Project.files()` instead.

**Comment by cy6erGn0m** [comment]
`getBuildDependencies` is not used in the frontend plugin, it must be some other plugin

**Comment by cy6erGn0m** [comment]
It is impossible to avoid extending `AbstractFileCollection` as it is required for internal gradle API (`DefaultSelfResolvingDependency`)

**Comment by snrostov** [comment]
Fixed in master. Will be released soon.
